### PR TITLE
floats: fix nearest, span and min/max index behaviours

### LINKED ISSUE #413: floats: Nearest() produces strange results with NaNs
When running this:
```
a := []float64{math.NaN(), 1, 2, 3}
b := 2
c := floats.Nearest(a, b)
```
Nearest returns 0, where I would expect 2. 
Since it's a simple matching, NaN can be also matched to a first occurrence in a slice like 
```
a := []float64{math.NaN(), 1, 2, 3}
b := math.NaN()
c := floats.Nearest(a, b)
// c == 0
```

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

I have not really touched the documentation, but I think that will probably need work too. Comments welcome for that.

Fixes #413.

/cc @aleh-null

### CODE REVIEW

File: floats/floats.go [hunk 1]
```diff
@@ -515,31 +515,109 @@ func NaNPayload(f float64) (payload uint64, ok bool) {
...
+// Nearest panics if len(s) == 0.
 func Nearest(s []float64, v float64) int {
+	if len(s) == 0 {
+		panic("floats: zero length slice")
+	}
+	switch {
+	case math.IsNaN(v):
+		return 0
+	case math.IsInf(v, 1):
+		return MaxIdx(s)
```
Comment (aleh-null) [inline floats/floats.go]: There is an issue with `MaxInd` as it does not handle NaNs "properly" in case first element is NaN(). Following tests will fail:
```
		{
			in:    []float64{math.NaN(), 0, -1, 2},
			query: math.Inf(1),
			want:  3,
			desc:  "Wrong index returned when query is +Inf and no +Inf element exists",
		},
		{
			in:    []float64{math.NaN(), 0, -1, 2},
			query: math.Inf(-1),
			want:  2,
			desc:  "Wrong index returned when query is -Inf and no -Inf element exists",
		}
```

Changing [this](https://github.com/gonum/gonum/blob/master/floats/floats.go#L436) to something like this
```
	var (
		max float64
		idx int
	)
	allnan := true
	for k, v := range x {
		if !math.IsNaN(v) {
			allnan = false
			idx, max = k, v
			break
		}
	}
	if allnan {
		return 0
	}
```

File: floats/floats.go [hunk 2]
```diff
@@ -515,31 +515,109 @@ func NaNPayload(f float64) (payload uint64, ok bool) {
...
+		if l == u {
+			return 0
+		}
+		if n%2 == 1 && !math.IsInf(v, 0) {
+			return n / 2
+		}
+		if math.Copysign(1, v) == math.Copysign(1, l) {
+			return 0
+		}
+		return n / 2
```
[the remark this answers is not in the document]
Comment (btracey) [reply floats/floats.go]: Are we sure this works for the case where n odd, v = +inf, and range = (-inf, +inf)?  Seems like it would return the index for 0 when it should be returning n/2+1

File: floats/floats.go [hunk 3]
```diff
@@ -515,31 +515,109 @@ func NaNPayload(f float64) (payload uint64, ok bool) {
...
+// NearestIdx return the index of a hypothetical vector created
 // by Span with length n and bounds l and u whose value is closest
-// to v. NearestWithinSpan panics if u < l. If the value is greater than u or
-// less than l, the function returns -1.
-func NearestWithinSpan(n int, l, u float64, v float64) int {
-	if u < l {
-		panic("floats: upper bound greater than lower bound")
+// to v. NearestIdx panics if n is zero.
+func NearestIdx(n int, l, u float64, v float64) int {
+	if n == 0 {
```
Comment (btracey) [inline floats/floats.go]: I think we should also panic if `l > u` (and in `Span`)

File: floats/floats.go [hunk 4]
```diff
@@ -733,6 +811,48 @@ func Span(dst []float64, l, u float64) []float64 {
 	if n < 2 {
 		panic("floats: destination must have length >1")
 	}
+
```
Comment (btracey) [inline floats/floats.go]: We'll need to add commentary about the NaN and Inf cases.

Comment (btracey) [reply floats/floats.go]: Panic if `l > u`?

File: floats/floats.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (btracey) [reply floats/floats.go]: Oh, looks like this was already pointed out. Thanks @aleh-null

File: floats/floats.go [hunk 5]
```diff
@@ -515,31 +515,109 @@ func NaNPayload(f float64) (payload uint64, ok bool) {
 // Nearest returns the index of the element in s
 // whose value is nearest to v.  If several such
 // elements exist, the lowest index is returned.
-// Panics if len(s) == 0.
+// Nearest panics if len(s) == 0.
```
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats.go]: Ah, that's what you meant.

File: floats/floats.go [hunk 6]
```diff
@@ -515,31 +515,109 @@ func NaNPayload(f float64) (payload uint64, ok bool) {
...
+		return MaxIdx(s)
+	case math.IsInf(v, -1):
+		return MinIdx(s)
+	}
 	var ind int
 	dist := math.Abs(v - s[0])
 	for i, val := range s {
 		newDist := math.Abs(v - val)
-		if newDist < dist {
+		// A NaN distance will not be closer.
```
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats.go]: The first loop panics for a completely NaN slice.

[the remark this answers is not in the document]
Comment (btracey) [reply floats/floats.go]: Yes, sorry, it should have `for i = 0; i < len(s); i++`

File: floats/floats.go (hunk 1 above)
Comment (kortschak) [reply floats/floats.go]: Fixed.

File: floats/floats.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats.go]: Done

File: floats/floats.go [hunk 7]
```diff
@@ -515,31 +515,109 @@ func NaNPayload(f float64) (payload uint64, ok bool) {
...
+		if !(newDist >= dist) {
 			dist = newDist
 			ind = i
 		}
 	}
 	return ind
 }
 
-// NearestWithinSpan return the index of a hypothetical vector created
+// NearestIdx return the index of a hypothetical vector created
```
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats.go]: Done

File: floats/floats.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats.go]: Fixed

File: floats/floats.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats.go]: The copysign is so that -0 is closer to -Inf.

File: floats/floats.go (hunk 3 above)
Comment (kortschak) [reply floats/floats.go]: I don't see any basis for prohibiting a descending span.

File: floats/floats.go (hunk 4 above)
Comment (kortschak) [reply floats/floats.go]: Same here.

File: floats/floats.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats.go]: This is fixed.

**Comment by kortschak** [comment]
PTAL

**Comment by kortschak** [comment]
>I'll look at tests when we agree on other behavior

It's probably worth looking at the tests first since they form a pseudo specification. TDD actually work quite well in this situation.

**Comment by aleh-null** [comment]
@kortschak @btracey can I help you in some way to close this one? It seems that everything was fixed besides documentation.

**Comment by kortschak** [comment]
You can give an informal approval, but I'm waiting on a review from another committer.

**Comment by aleh-null** [comment]
@kortschak LGTM

File: floats/floats_test.go [hunk 8]
```diff
@@ -919,8 +1038,57 @@ func TestNearestWithinSpan(t *testing.T) {
...
+			upper:  math.Inf(1),
+			value:  0,
+			idx:    2,
+		},
+		{
+			length: 4,
+			lower:  math.Inf(-1),
+			upper:  math.Inf(1),
+			value:  math.Inf(1),
+			idx:    2,
```
Comment (vladimir-ch) [inline floats/floats_test.go]: Why is the expected `idx` not 3? It seems wrong that `0` and `inf` lead to same `idx`.

Comment (btracey) [reply floats/floats_test.go]: The (hypothetical) slice is []float64{-inf, -inf, inf, inf}. -0 is closer to -inf, +0 is closer to inf. This way they both return idx = 2.

Comment (vladimir-ch) [reply floats/floats_test.go]: Thanks, seeing the hypothetical slice explains it. But documenting the behavior regarding all the possible combinations of corner values and for the user to understand it, should this function really be in Gonum?

File: floats/floats_test.go [hunk 9]
```diff
@@ -26,6 +27,26 @@ func AreSlicesEqual(t *testing.T, truth, comp []float64, str string) {
 	}
 }
 
+func AreSlicesSame(t *testing.T, truth, comp []float64, str string) {
```
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats_test.go]: fd4ca875, it was copy pasted.

File: floats/floats_test.go [hunk 10]
```diff
@@ -1159,6 +1327,57 @@ func TestSpan(t *testing.T) {
...
+			want: []float64{math.Inf(1), math.NaN(), math.NaN(), math.NaN(), math.NaN()},
+		},
+		{
+			n: 5, l: math.NaN(), u: math.Inf(-1),
+			want: []float64{math.NaN(), math.NaN(), math.NaN(), math.NaN(), math.Inf(-1)},
+		},
+		{
+			n: 5, l: math.NaN(), u: math.Inf(1),
+			want: []float64{math.NaN(), math.NaN(), math.NaN(), math.NaN(), math.Inf(1)},
+		},
```
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats_test.go]: Done x6

File: floats/floats.go [hunk 11]
```diff
@@ -433,9 +433,12 @@ func MaxIdx(s []float64) int {
 	if len(s) == 0 {
 		panic("floats: zero slice length")
 	}
-	max := s[0]
+	max := math.Inf(-1)
 	var ind int
 	for i, v := range s {
+		if math.IsNaN(v) {
```
[the remark this answers is not in the document]
Comment (kortschak) [reply floats/floats.go]: Also MinAndIdx

File: floats/floats_test.go (hunk 8 above)
Comment (vladimir-ch) [reply floats/floats_test.go]: Why the hypothetical slice is `[]float64{-inf, -inf, inf, inf}`? If `n` is odd, does it have 0 in the middle? Why?

Comment (btracey) [reply floats/floats_test.go]: It seems like the only logical behavior since it's halfway between the two.

`Span` shouldn't be used if there are NaN and Inf involved. It is a very reasonable function without those limiting cases. However, the input cannot be finite numbers, so we have to have behavior with inf and nan inputs. We can either panic with those inputs, or try to do something sensible. It's not clear to me which is worse here, but neither is good.

File: floats/floats.go [hunk 12]
```diff
@@ -512,34 +521,117 @@ func NaNPayload(f float64) (payload uint64, ok bool) {
...
 // by Span with length n and bounds l and u whose value is closest
-// to v. NearestWithinSpan panics if u < l. If the value is greater than u or
-// less than l, the function returns -1.
-func NearestWithinSpan(n int, l, u float64, v float64) int {
-	if u < l {
-		panic("floats: upper bound greater than lower bound")
+// to v. That is, NearestIdxForSpan(n, l, u, v) is equivalent to
+// Nearest(Span(make([]float64, n),l,u),v) without an allocation and
+// with a relaxation for the paramater n.
+// NearestIdxForSpan panics if n is less than one.
```
Comment (vladimir-ch) [inline floats/floats.go]: This should be `n is less than two`, shouldn't it?

File: floats/floats_test.go (hunk 8 above)
Comment (vladimir-ch) [reply floats/floats_test.go]: > logical behavior since it's halfway between the two.

That's probably the essence of my unease with this. I don't think it's logical because I don't think there's anything halfway between -inf and +inf. Or that it is clear how a hypothetical slice from -inf to 3 (for example) looks like (I really don't know, I guess it would be something like `[]float{-inf, -inf, -inf, 3}`).

The output seems to be useful only if the inputs are finite numbers, so the user will not be able to blindly pass numbers in and use the result anyway, so I would vote for panicking. But much work has went into this and there are rules with reasoning behind them, so if they are documented, then LGTM too.

File: floats/floats.go (hunk 12 above)
Comment (vladimir-ch) [reply floats/floats.go]: Or is this what "a relaxation" means? How the hypothetical vector looks like for `n = 1`?

Comment (btracey) [reply floats/floats.go]: Yes, I agree, this should panic for `n  < 2`, so that it matches `Span`

File: floats/floats_test.go (hunk 8 above)
Comment (vladimir-ch) [reply floats/floats_test.go]: SGTM

File: floats/floats.go (hunk 12 above)
Comment (kortschak) [reply floats/floats.go]: OK

File: floats/floats_test.go (hunk 8 above)
Comment (kortschak) [reply floats/floats_test.go]: I will remove the documentation of the special cases.

**Comment by kortschak** [comment]
PTAL
