### PR TITLE
mat: add example for polynomial regression with QR factorization

### LINKED ISSUE #1759: Would you mind writing a quick demo about "polyfit" and "polyval"? Thank you.
In matlab and numpy. There are build-in functions like "polyfit" and "polyval".
I searched some codes like https://rosettacode.org/wiki/Polynomial_regression#Library_gonum.2Fmatrix
But all of them are out of date (Use old library mat64).
I am not really good at math. I tried to understand QR matrix and wrote it myself but failed. Would you mind writing a quick demo about "polyfit" and "polyval" with QR matrix? Thank you for your help.

### PR DESCRIPTION
**Pull request by sbinet**
Fixes #1759.

Signed-off-by: Sebastien Binet <binet@cern.ch>

Please take a look.

### CODE REVIEW

File: mat/qr_example_test.go [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+import (
+	"fmt"
+	"log"
+
+	"gonum.org/v1/gonum/mat"
+)
+
+func ExampleQR_solveTo() {
+	var (
```
Comment (kortschak) [inline mat/qr_example_test.go:15]: This probably wants some lead in text.

File: mat/qr_example_test.go [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+	}
+	fmt.Printf("%.3f\n", mat.Formatted(c))
+
+	// Output:
+	// ⎡1.000⎤
+	// ⎢2.000⎥
+	// ⎣3.000⎦
+}
+
+func Vandermonde(a []float64, d int) *mat.Dense {
```
Comment (kortschak) [inline mat/qr_example_test.go:42]: Is there a particular reason to use this rather than just demonstrating a solve with a product of two matrices? If this is needed it should be introduced in the lead in text so that readers aren't required to look up and understand the background for this in order to understand the QR solve API.

Comment (sbinet) [reply mat/qr_example_test.go]: no reason.
I was just implementing the Rosetta code example for QR factorization (that I had migrated from `github.com/gonum/matrix` to `gonum.org/v1/gonum/mat`)
https://rosettacode.org/wiki/Polynomial_regression#Library_gonum.2Fmatrix

File: mat/qr_example_test.go [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+	var (
+		a = mat.NewDense(4, 2, []float64{0, 1, 1, 1, 1, 1, 2, 1})
+		b = mat.NewDense(4, 1, []float64{1, 0, 2, 1})
+		x = mat.NewDense(2, 1, nil)
+	)
+
+	var qr mat.QR
+	qr.Factorize(a)
+
+	const trans = false
```
Comment (kortschak) [inline mat/qr_example_test.go:31]: This will be rendered right next to the documentation, so I don't think this const is necessary.

**Review by kortschak — DISMISSED** [review]

**Comment by sbinet** [comment]
PTAL

**Review by kortschak — APPROVED** [review]
Thanks
