### PR TITLE
stat: ROC revert functionality when cutoffs is not nil, code readability improvements, and bug fixes

### LINKED ISSUE #1557: stat: ROC does not correctly handle bins beyond highest observation
### What are you trying to do?
package main

import (
	"fmt"
	"math"
	"gonum.org/v1/gonum/stat"
)

func main() {
	scores := []float64{0.1, 0.35, 0.4, 0.8}
	classes := []bool{true, false, true, false}
	cutoffs := []float64{math.Inf(-1), 0.1, 0.35, 0.4, 0.8, 0.9, 1}
	tpr, fpr, thresh := stat.ROC(cutoffs, scores, classes, nil)
	fmt.Printf("true  positive rate: %v\n", tpr)
	fmt.Printf("false positive rate: %v\n", fpr)
	fmt.Printf("thresh: %v\n", thresh)
}

### What did you expect to happen?
true  positive rate: [0 0 0 0 0.5 0.5 1]
false positive rate: [0 0 0 0.5 0.5 1 1]
thresh: [+Inf 1 0.9 0.8 0.4 0.35 0.1]

### What actually happened?
true  positive rate: [1 1 0 0 0.5 0.5 1]
false positive rate: [1 1 0 0.5 0.5 1 1]
thresh: [+Inf 1 0.9 0.8 0.4 0.35 0.1]

### What version of Go and Gonum are you using?

go version
go version go1.15.6 windows/amd64

rg gonum.org/v1/gonum go.sum
18:gonum.org/v1/gonum v0.0.0-20180816165407-929014505bf4/go.mod h1:Y+Yx5eoAFn32cQvJDxZx5Dpnq+c3wtXuadVZAcxbbBo=

### Does this issue reproduce with the current master?
require gonum.org/v1/gonum v0.8.2

### PR DESCRIPTION
**Pull request by Armadilloa16**
The main change is when cutoffs is not nil, returned thresholds are now cutoffs (sorted in decreasing order), and the fpr and tpr values are such that they are correct for these thresholds. 

This: 
 - maintains the parity convention decision made in #316 and documented in the ROC description.
 - is (I believe) closer to the original intent of #708
 - should resolve #1557 and #1559 (although changes the expected output)
 - includes extra test case from #1557 as per #1558

### CODE REVIEW

File: stat/roc.go [hunk 1]
```diff
@@ -98,28 +96,35 @@ func ROC(cutoffs, y []float64, classes []bool, weights []float64) (tpr, fpr, thr
...
+		tpr[bin] = tpr[bin-1]
+		fpr[bin] = fpr[bin-1]
+	}
 
 	invNeg := 1 / nNeg
 	invPos := 1 / nPos
 	for i := range tpr {
 		// Prevent fused float operations by
 		// making explicit float64 conversions.
+		// Convert negative counts to TPR and FPR
```
Comment (kortschak) [inline stat/roc.go:119]: I think this would be better above the for loop. Also add final full stop.

File: stat/roc.go [hunk 2]
```diff
@@ -98,28 +96,35 @@ func ROC(cutoffs, y []float64, classes []bool, weights []float64) (tpr, fpr, thr
 		}
 		nPos += posWeight
 		nNeg += negWeight
-		if y[i] <= cutoffs[bin] {
+		if y[i] < cutoffs[bin] {
+			// Actually counting false negatives
```
Comment (kortschak) [inline stat/roc.go:102]: Full stops for sentences.

File: stat/roc.go [hunk 3]
```diff
@@ -98,28 +96,35 @@ func ROC(cutoffs, y []float64, classes []bool, weights []float64) (tpr, fpr, thr
...
 			tpr[bin] += posWeight
+			// Actually counting true negatives
 			fpr[bin] += negWeight
 		}
 	}
+	for bin < len(cutoffs)-1 {
+		bin++
+		tpr[bin] = tpr[bin-1]
+		fpr[bin] = fpr[bin-1]
+	}
```
Comment (kortschak) [inline stat/roc.go:112]:
```
lastTpr = tpr[bin]
lastFpr = fpr[bin]
for bin++; bin < len(cutoffs); bin++ {
    tpr[bin] = lastTpr
    fpr[bin] = lastFpr
}
```

File: stat/roc.go [hunk 4]
```diff
@@ -55,12 +55,9 @@ func ROC(cutoffs, y []float64, classes []bool, weights []float64) (tpr, fpr, thr
 	if len(cutoffs) == 0 {
 		if cutoffs == nil || cap(cutoffs) < len(y)+1 {
 			cutoffs = make([]float64, len(y)+1)
-		} else {
-			cutoffs = cutoffs[:len(y)+1]
 		}
-		cutoffs[0] = math.Inf(-1)
 		// Choose all possible cutoffs for unique values in y.
-		bin := 1
+		var bin int
```
Comment (kortschak) [inline stat/roc.go:62]: `bin := 0`

File: stat/roc_test.go [hunk 5]
```diff
@@ -210,6 +210,14 @@ func TestROC(t *testing.T) {
 			wantFPR:    nil,
 			wantThresh: nil,
 		},
+		{ // 23
```
Comment (kortschak) [inline stat/roc_test.go:213]: Can you add a test case for #1559.

```
		{ // 24
			y:          []float64{0.1, 0.35, 0.4, 0.8},
			c:          []bool{true, false, true, false},
			cutoffs:    []float64{-1, 0, 0.1, 0.36, 0.8},
			wantTPR:    []float64{...
			wantFPR:    []float64{...
			wantThresh: []float64{...
		},
```

File: stat/roc.go (hunk 1 above)
Comment (Armadilloa16) [reply stat/roc.go]: Yep

File: stat/roc.go (hunk 2 above)
Comment (Armadilloa16) [reply stat/roc.go]: Yep

File: stat/roc.go (hunk 3 above)
Comment (Armadilloa16) [reply stat/roc.go]: Yeah that makes sense.

File: stat/roc.go (hunk 4 above)
Comment (Armadilloa16) [reply stat/roc.go]: Ok

File: stat/roc_test.go (hunk 5 above)
Comment (Armadilloa16) [reply stat/roc_test.go:213]: Done.

File: stat/roc.go [hunk 6]
```diff
@@ -98,14 +98,22 @@ func ROC(cutoffs, y []float64, classes []bool, weights []float64) (tpr, fpr, thr
...
+	lastFpr := fpr[bin]
+	for bin++; bin < len(cutoffs); bin++ {
+		tpr[bin] = lastTpr
+		fpr[bin] = lastFpr
+	}
 
 	invNeg := 1 / nNeg
 	invPos := 1 / nPos
+	// Convert negative counts to TPR and FPR.
 	for i := range tpr {
```
Comment (kortschak) [inline stat/roc.go:117]: Out of curiosity (and laziness), does [my approach](https://github.com/gonum/gonum/pull/1558/files#diff-07d8944b2b9171f3dfbb983bfc016c30c93b829e6d2b2c4c91b21de24f3c8dccR109) used in #1558 work? It's simpler than this and does less work.

Comment (Armadilloa16) [reply stat/roc.go:117]: I could be wrong, but I think the case for which it wouldn't work is when there are more cutoffs above the maximum y value, I added a test case for this case (test case 26). I agree your solution is prettier though.

Comment (kortschak) [reply stat/roc.go:117]: Just tested with your new cases and yes, this simpler approach is correct.

Comment (Armadilloa16) [reply stat/roc.go:117]: Huh, yes I see what you mean now. This is confusing, but I believe it is actually equivalent. How about I incorporate you're simpler approach, but also add a comment to try and explain what it's doing?

Comment (kortschak) [reply stat/roc.go]: SGTM. I would say,

```
// Convert negative counts to TPR and FPR for non-zero bins.
```

Note that the reason this works is that these bins are zero in the final result, but `make` has already initialised the elements to be zero. So we just work on bins that are non-zero and use the existing zeros for the final result.

File: stat/roc.go [hunk 7]
```diff
@@ -104,17 +104,13 @@ func ROC(cutoffs, y []float64, classes []bool, weights []float64) (tpr, fpr, thr
...
 		}
 	}
-	lastTpr := tpr[bin]
-	lastFpr := fpr[bin]
-	for bin++; bin < len(cutoffs); bin++ {
-		tpr[bin] = lastTpr
-		fpr[bin] = lastFpr
-	}
+	// here bins beyond the maximum value in y are skipped, and the
+	// fpr and tpr are set to zero below by ommission.
```
Comment (kortschak) [inline stat/roc.go]: I'd put this after the comment with the for loop.

```
	// Bins beyond the maximum value in y are skipped
	//  and the fpr and tpr elements are left as zero.
```

File: stat/roc.go (hunk 6 above)
Comment (Armadilloa16) [reply stat/roc.go]: Yeah, cool. It's always an interesting tradeoff between efficiency and clarity. I suppose that's the point of comments. You happy for me to squash all these commit's together now?

Comment (kortschak) [reply stat/roc.go]: Yes, please. Note that this is not strictly a reversion. I'd say "stat: fix ROC cutoffs".

Do you want/need to add UWA to AUTHORS (separate commit)?

File: stat/roc.go (hunk 7 above)
Comment (Armadilloa16) [reply stat/roc.go]: Done (?).

Comment (kortschak) [reply stat/roc.go]: LGTM

File: stat/roc.go (hunk 6 above)
Comment (Armadilloa16) [reply stat/roc.go]: Sounds good. 

Hmm, no need to add UWA but maybe I should change the contact to my personal gmail, because I don't have access to the adelaide email address anymore... good point.

Comment (kortschak) [reply stat/roc.go]: OK. Make that a new PR. It would just be adding your personal email address to the lines in A+C.

File: stat/roc.go [hunk 8]
```diff
@@ -98,15 +98,19 @@ func ROC(cutoffs, y []float64, classes []bool, weights []float64) (tpr, fpr, thr
...
 		nNeg += negWeight
-		if y[i] <= cutoffs[bin] {
+		// Count false negatives (in tpr) and true negatives (in fpr).
+		if y[i] < cutoffs[bin] {
 			tpr[bin] += posWeight
 			fpr[bin] += negWeight
 		}
 	}
+	// Bins beyond the maximum value in y are skipped
+	// leaving these fpr and tpr elements as zero.
```
Comment (kortschak) [inline stat/roc.go:108]: Sorry, this should be after L112, just before the for loop.

Comment (Armadilloa16) [reply stat/roc.go:108]: Oh yeah that makes sense

**Review by kortschak — APPROVED** [review]
Thanks

**Comment by kortschak** [comment]
Do you need me to merge?

**Comment by Armadilloa16** [comment]
Sure, I don't think I have merge rights. All looks good to me.
