### PR TITLE
stat: handle non-unique results in test for PC

### LINKED ISSUE #21: stat: PCA fails with noasm or appengine build tags
The failure is due to numerical stability and only really shows up in the lowest valued column.

### PR DESCRIPTION
**Pull request by vladimir-ch**
Please take a look.

Closes #21

### CODE REVIEW

File: stat/pca_test.go [hunk 1]
```diff
@@ -163,14 +159,37 @@ tests:
 				t.Errorf("unexpected SVD failure for test %d use %d", i, j)
 				continue tests
 			}
-			if !mat.EqualApprox(vecs, test.wantVecs, test.epsilon) {
+
+			// Find the number of non-zero variances to handle
+			// non-uniqueness in SVD result (issue #21).
+			nnz := len(vars)
+			for k, v := range vars {
+				if math.Abs(v) < 1e-15 {
```
Comment (kortschak) [inline stat/pca_test.go]: Can we change this to 
```
const epsilon 1e-15
if math.Abs(v) < epsilon {
```

Comment (vladimir-ch) [reply stat/pca_test.go]: Done
